-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
    SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A
USING (AUTHOR_ID)
JOIN BOOK_SALES AS S
USING (BOOK_ID)
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;