-- 코드를 작성해주세요
# ITEM_TREE에서 ITEM_ID가 PARENT_ITEM_ID에 없으면 더이상 업그레이드x
WITH PARENT AS (
    SELECT DISTINCT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
),
NOT_UPGRADE AS (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM PARENT)
)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT ITEM_ID FROM NOT_UPGRADE)
ORDER BY ITEM_ID DESC;