-- 코드를 작성해주세요
# ITEM_TREE에서 ITEM_ID가 PARENT_ITEM_ID에 없으면 더이상 업그레이드x
# WITH PARENT AS (
#     SELECT DISTINCT PARENT_ITEM_ID
#     FROM ITEM_TREE
#     WHERE PARENT_ITEM_ID IS NOT NULL
# )

# SELECT ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO
# WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM PARENT)
# ORDER BY ITEM_ID DESC;



SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
LEFT JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;