-- 코드를 작성해주세요
WITH CHILD AS (
    SELECT PARENT_ID, COUNT(ID) AS COUNT  
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)

SELECT ID, IFNULL(C.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT JOIN CHILD AS C
ON E.ID = C.PARENT_ID
ORDER BY ID ASC;