-- 코드를 작성해주세요
# SELECT A.ID AS ID, IFNULL(B.COUNT, 0) AS CHILD_COUNT
# FROM ECOLI_DATA AS A
# LEFT JOIN(
#     SELECT PARENT_ID, COUNT(*) AS COUNT
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NOT NULL
#     GROUP BY PARENT_ID) AS B
# ON A.ID = B.PARENT_ID    
# ORDER BY ID ASC;

SELECT ID, (
    SELECT COUNT(*) 
    FROM ECOLI_DATA AS CHILD 
    WHERE CHILD.PARENT_ID = PARENT.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT
ORDER BY PARENT.ID ASC;