-- 코드를 입력하세요
WITH CAR AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' 
        AND END_DATE >= '2022-11-01'        
)


SELECT C.CAR_ID, C.CAR_TYPE, 
    CAST(30 * C.DAILY_FEE * (1 - DISCOUNT_RATE * 0.01) AS SIGNED) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    USING (CAR_TYPE)
    WHERE C.CAR_ID NOT IN (SELECT * FROM CAR) 
        AND C.CAR_TYPE IN ('세단', 'SUV')
        AND P.DURATION_TYPE = '30일 이상'
        AND (30 * C.DAILY_FEE * (1 - DISCOUNT_RATE * 0.01)) >= 500000
        AND (30 * C.DAILY_FEE * (1 - DISCOUNT_RATE * 0.01)) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
