-- 코드를 작성해주세요
WITH PERCENT_ECOLI_DATA AS (
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY) AS PERCENT
    FROM ECOLI_DATA
)

SELECT 
    ID, 
    CASE
        WHEN PERCENT >= 0.75 THEN 'CRITICAL'
        WHEN PERCENT >= 0.5 THEN 'HIGH'
        WHEN PERCENT >= 0.25 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM PERCENT_ECOLI_DATA
ORDER BY ID ASC;