# -- 코드를 입력하세요
# WITH USER AS (
#     SELECT U.USER_ID
#     FROM USED_GOODS_USER AS U
#     JOIN USED_GOODS_BOARD AS B
#     ON U.USER_ID = B.WRITER_ID
#     GROUP BY U.USER_ID
#     HAVING COUNT(*) >= 3
# )

# SELECT USER_ID, NICKNAME, 
#     CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소', 
#     CONCAT(LEFT(TLNO, 3), '-', SUBSTRING(TLNO, 4, 4), '-', RIGHT (TLNO, 4)) AS '전화번호'
# FROM USED_GOODS_USER
# WHERE USER_ID IN (SELECT * FROM USER)
# ORDER BY USER_ID DESC;



SELECT USER_ID, NICKNAME,
CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS 전체주소,
CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER
WHERE (
    SELECT COUNT(*) FROM USED_GOODS_BOARD
    WHERE USER_ID = WRITER_ID) >= 3
ORDER BY USER_ID DESC