-- 코드를 입력하세요
SELECT INFO.REST_ID AS REST_ID, 
    INFO.REST_NAME AS REST_NAME, 
    INFO.FOOD_TYPE AS FOOD_TYPE, 
    INFO.FAVORITES AS FAVORITES, 
    INFO.ADDRESS AS ADDRESS, 
    # REVIEW.REVIEW_SCORE
    ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS INFO
JOIN REST_REVIEW AS REVIEW
ON INFO.REST_ID = REVIEW.REST_ID
WHERE INFO.ADDRESS LIKE '서울%'
GROUP BY INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;

# SELECT REST_ID, REVIEW_ID, AVG(REVIEW_SCORE)
# FROM REST_REVIEW
# GROUP BY REST_ID;

# SELECT REST_ID, REVIEW_ID, REVIEW_SCORE
# FROM REST_REVIEW;
