-- 코드를 입력하세요
WITH USER_INFO_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM USER_INFO_2021), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO_2021)
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;

# 2021년 가입
# 년, 월 별로 >> 상품 구매 회원수, 상품 구매 비율(소수점 첫번째 자리까지 반올림)
# 년을 기준 오름차순, 월 기준 오름차순