-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_INFO AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA AS E
    JOIN GENERATION_INFO AS G
    ON E.PARENT_ID = G.ID
)

SELECT 
    COUNT(*) AS COUNT, 
    GENERATION
FROM GENERATION_INFO
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM GENERATION_INFO
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;