-- 코드를 작성해주세요
# 재귀 사용

# (ID, 부모ID, N세대)
WITH RECURSIVE GENERATION AS (
    SELECT ID
        , PARENT_ID
        , 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID
        , E.PARENT_ID
        , GEN + 1 AS GEN
    FROM ECOLI_DATA E
    JOIN GENERATION G
        ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT
    , GEN AS GENERATION
FROM GENERATION
# 자식이 없다
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM GENERATION WHERE PARENT_ID IS NOT NULL)
GROUP BY GEN;

# 자식이 있는 경우 
# SELECT ID FROM ECOLI_DATA
# WHERE ID NOT IN 
# (
#     SELECT PARENT_ID
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NOT NULL
#     GROUP BY PARENT_ID
#     HAVING COUNT(*) > 0);


# 자식이 있는 경우 PARENT_ID >> PARENT_ID가 NULL인 경우도 있으므로 not null 조건 추가 
# SELECT PARENT_ID
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NOT NULL
#     GROUP BY PARENT_ID
#     HAVING COUNT(*) > 0;
