-- 코드를 입력하세요
WITH ORDERS AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) 

SELECT F.PRODUCT_ID, F.PRODUCT_NAME, F.PRICE * O.TOTAL AS TOTAL_SALES
FROM FOOD_PRODUCT AS F
JOIN ORDERS AS O
USING (PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;