-- 코드를 입력하세요
WITH JULY_FLAVOR AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN JULY_FLAVOR AS J
USING (FLAVOR)
ORDER BY F.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3;

# FIRST_HALF >> SHIPMENT_ID(FK), FLAVOR(PK), TOTAL_ORDER
# JULY >> SHIPMENT_ID(PK), FLAVOR(FK), TOTAL_ORDER >> 동일한 FLAVOR, 다른 SHIPMENT_ID 가능