-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
    # DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d %H:%m:%s') AS APNT_YMD
FROM APPOINTMENT AS A
JOIN DOCTOR AS D
ON A.MDDR_ID = D.DR_ID
JOIN PATIENT AS P
ON A.PT_NO = P.PT_NO
# 2022-04-13 취소x, CS 
WHERE 
    A.APNT_CNCL_YN = 'N'
    AND A.MCDP_CD = 'CS'
    AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY APNT_YMD ASC;