-- 코드를 입력하세요
WITH RECURSIVE TIMES AS (
    SELECT 0 AS HOUR
    FROM DUAL
    
    UNION ALL
    
    SELECT HOUR + 1 AS HOUR
    FROM TIMES
    WHERE HOUR < 23
)


SELECT HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS O
RIGHT JOIN TIMES AS T
ON HOUR(O.DATETIME) = T.HOUR
GROUP BY HOUR
ORDER BY HOUR ASC;