-- 코드를 작성해주세요
WITH RARE_ITEM AS (
    SELECT *
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
), RARE_CHILD_ITEM AS (
    SELECT T.ITEM_ID
    FROM ITEM_TREE AS T
    JOIN RARE_ITEM AS R
    ON T.PARENT_ITEM_ID = R.ITEM_ID
)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT ITEM_ID FROM RARE_CHILD_ITEM
)
ORDER BY ITEM_ID DESC;


# ITEM_TREE 에서 PARENT_ITEM_ID가 희귀 아이템의 ID인 경우 해당 ITEM_TREE의 ITEM_ID를 이용해 조회