-- 코드를 작성해주세요
# WITH YEAR_MAX AS (
#     SELECT 
#         DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
#     FROM ECOLI_DATA
#     GROUP BY YEAR
# )

# SELECT 
#     DATE_FORMAT(E.DIFFERENTIATION_DATE, '%Y') AS YEAR, 
#     Y.MAX - E.SIZE_OF_COLONY AS YEAR_DEV, 
#     E.ID
# FROM ECOLI_DATA AS E
# JOIN YEAR_MAX AS Y
# ON DATE_FORMAT(E.DIFFERENTIATION_DATE, '%Y') = Y.YEAR
# ORDER BY YEAR ASC, YEAR_DEV ASC;

-- 코드를 작성해주세요
WITH MAX_SIZE_OF_COLONY AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A
JOIN MAX_SIZE_OF_COLONY B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;

# SELECT DATE_FORMAT(DIFFERENTIATION_DATE, '%Y'), YEAR(DIFFERENTIATION_DATE)
# FROM ECOLI_DATA;