-- 코드를 작성해주세요
WITH MAX_FISH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO AS N
JOIN FISH_INFO AS I
USING (FISH_TYPE)
WHERE (I.FISH_TYPE, I.LENGTH) IN (SELECT FISH_TYPE, MAX_LENGTH FROM MAX_FISH)
ORDER BY ID ASC;
