-- 코드를 입력하세요
# SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
# FROM BOOK 
# WHERE YEAR(PUBLISHED_DATE) = '2021' AND CATEGORY = '인문'
# ORDER BY BOOK_ID;

SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK 
WHERE PUBLISHED_DATE like '2021%' AND CATEGORY = '인문'
ORDER BY BOOK_ID;


# MySQL에서 TO_CHAR는 지원하지 않는다. 오라클은 지원
# SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'yyyy-mm-dd')
# FROM BOOK
# WHERE TO_CHAR(PUBLISHED_DATE, 'yyyy-mm-dd') LIKE '2021%'
# AND CATEGORY = '인문'
# ORDER BY PUBLISHED_DATE ASC;