-- 코드를 작성해주세요
WITH SCORES AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT S.SCORE, S.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES AS E
JOIN SCORES AS S
USING (EMP_NO)
ORDER BY S.SCORE DESC
LIMIT 1;
