-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, 
R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B
RIGHT JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

# SELECT 
# 	TITLE, 
#     BOARD.BOARD_ID, 
#     REPLY_ID, 
#     REPLY.WRITER_ID, 
#     REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_REPLY AS REPLY
# LEFT JOIN USED_GOODS_BOARD AS BOARD
# ON REPLY.BOARD_ID = BOARD.BOARD_ID
# # BOARD.CREATED_DATE <= '2022-10-31'
# WHERE DATE_FORMAT(BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
# ORDER BY REPLY.CREATED_DATE, TITLE;